// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXaZ1nhALcB_r0N4rWTBSo8Z_JDBfmif0',
    appId: '1:526415717285:web:aa9c705391d719c7a07e4c',
    messagingSenderId: '526415717285',
    projectId: 'yz-muhasebe-app',
    authDomain: 'yz-muhasebe-app.firebaseapp.com',
    storageBucket: 'yz-muhasebe-app.firebasestorage.app',
    measurementId: 'G-3M0SH3NJE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAT9NTUZ-zwwzz3UPrRGMagpErtm7Zuw8',
    appId: '1:526415717285:android:9c9a2c291f58af91a07e4c',
    messagingSenderId: '526415717285',
    projectId: 'yz-muhasebe-app',
    storageBucket: 'yz-muhasebe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8WIw_PCiBLSTtBmth7GK35U8K5lrvrJ0',
    appId: '1:526415717285:ios:478271c69199f302a07e4c',
    messagingSenderId: '526415717285',
    projectId: 'yz-muhasebe-app',
    storageBucket: 'yz-muhasebe-app.firebasestorage.app',
    iosBundleId: 'com.example.yzMuhasebeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8WIw_PCiBLSTtBmth7GK35U8K5lrvrJ0',
    appId: '1:526415717285:ios:478271c69199f302a07e4c',
    messagingSenderId: '526415717285',
    projectId: 'yz-muhasebe-app',
    storageBucket: 'yz-muhasebe-app.firebasestorage.app',
    iosBundleId: 'com.example.yzMuhasebeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXaZ1nhALcB_r0N4rWTBSo8Z_JDBfmif0',
    appId: '1:526415717285:web:7c77437dd0cadba5a07e4c',
    messagingSenderId: '526415717285',
    projectId: 'yz-muhasebe-app',
    authDomain: 'yz-muhasebe-app.firebaseapp.com',
    storageBucket: 'yz-muhasebe-app.firebasestorage.app',
    measurementId: 'G-YZ9DPE99EN',
  );

}